apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

patchesStrategicMerge:
- deployment.yml
- auth.yml

resources:
- ../../base
## userAuth enabled - Oathkeeper proxies to backend instead of ingress
# - ingress.yml

- pdb.yml

configMapGenerator:
- name: deployable0504-config
  behavior: merge
  literals:
    - ENVIRONMENT=production
    - BACKEND_HOST=api.zero-david.online
    - FRONTEND_HOST=app.zero-david.online
